import psycopg2
from datetime import datetime

DB_CONFIG = {
    "host": "localhost",
    "database": "HeartRate",
    "user": "postgres",
    "password": "1230",
    "port": "5432"
}

def connect_db():
    try:
        connection = psycopg2.connect(**DB_CONFIG)
        cursor = connection.cursor()
        print("Connection established!")
        return connection, cursor
    except Exception as error:
        print(f"error: {error}")
        return None, None

def create_heartbeats_table(cursor, connection):
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS public.home_heartbeats (
            id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
            user_id bigint NOT NULL,
            tag_no character varying(20) COLLATE pg_catalog."default",
            date timestamp with time zone NOT NULL,
            description character varying(250) COLLATE pg_catalog."default",
            heart_beats numeric(3,0),
            CONSTRAINT home_heartbeats_pkey PRIMARY KEY (id)
        );
    """)
    connection.commit()
    print("The table was created or already existed.")

def create_home_heartbeats_count_table(cursor, connection):
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS public.home_heartbeats_count (
            id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
            rate_id bigint REFERENCES public.home_heartbeats(id),
            heartbeats_count_number integer NOT NULL
            CONSTRAINT home_heartbeats_pkey PRIMARY KEY (id)

        );
    """)
    connection.commit()
    print("The home_heartbeats_count table was created or already exists.!")

def save_heart_rate(user_id, bpm, tag_no=None, description=None):
    connection, cursor = connect_db()
    if connection:
        # Create table if it does not exist
        create_heartbeats_table(cursor, connection)
        # Insert data
        current_time = datetime.now()
        cursor.execute("""
            INSERT INTO public.home_heartbeats (user_id, tag_no, date, description, heart_beats)
            VALUES (%s, %s, %s, %s, %s) RETURNING id
        """, (user_id, tag_no, current_time, description, bpm))
        rate_id = cursor.fetchone()[0]  # Get rate_id
        connection.commit()
        print("Heart beat saved!")
        cursor.close()
        connection.close()
        return rate_id  

def save_home_heartbeats_count(rate_id, count):
    connection, cursor = connect_db()
    if connection:
        cursor.execute("""
            INSERT INTO public.home_heartbeats_count (rate_id, heartbeats_count_number)
            VALUES (%s, %s)
        """, (rate_id, count))
        connection.commit()
        cursor.close()
        connection.close()
        print("Heart beat saved!")

if __name__ == "__main__":
    save_heart_rate(1, 75, "test_tag", "تست ضربان قلب")